version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: ikasmadapangkep-app
        restart: unless-stopped
        environment:
            - APP_NAME=Ikatan Alumni Smada Pangkep
            - APP_ENV=local
            - APP_KEY=base64:WXHTCR6B4gI9taXRvygHlI+itx/4RH+L6+Or2DcNkSs=
            - APP_DEBUG=true
            - APP_URL=http://localhost:8001
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=ikasmadapangkep
            - DB_USERNAME=ikasmadapangkepuser
            - DB_PASSWORD=secret
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - REDIS_PASSWORD=
            - FIREBASE_PROJECT=ikasmadapangkep
            - FIREBASE_PROJECT_ID=
            - FIREBASE_CREDENTIALS=/app/storage/app/firebase/firebase-credentials.json
            - IS_REPLICA=true
            - REPLICA_WEIGHT=1
        volumes:
            - .:/app:delegated
            - ./node_modules:/app/node_modules
            - /app/vendor
            - ./storage/app/firebase:/app/storage/app/firebase:ro
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        ports:
            - "8001:8001"
        depends_on:
            - db
            - redis
        networks:
            - ikasmadapangkep

    db:
        image: mysql:8.0
        container_name: ikasmadapangkep-db
        restart: unless-stopped
        command: --default-time-zone='Asia/Makassar'
        environment:
            MYSQL_DATABASE: ikasmadapangkep
            MYSQL_USER: ikasmadapangkepuser
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: rootpassword
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        networks:
            - ikasmadapangkep

    redis:
        image: redis:alpine
        container_name: ikasmadapangkep-redis
        restart: unless-stopped
        command: redis-server /usr/local/etc/redis/redis.conf
        ports:
            - "6379:6379"
        volumes:
            - redisdata:/data
            - ./redis.conf:/usr/local/etc/redis/redis.conf
        networks:
            - ikasmadapangkep

networks:
    ikasmadapangkep:
        driver: bridge

volumes:
    dbdata:
    redisdata:
